# Base rules enabled
default: true

# MD007: Unordered list indentation (clean structure)
MD007:
    indent: 4

# MD009: No trailing spaces (avoid noisy diffs)
MD009: true

# MD013: Line length: readable for prose, flexible for code
MD013:
    line_length: 512
    code_blocks: false
    tables: false

# MD024: Only forbid duplicate headings at the same level
MD024:
    siblings_only: true

# MD026: Allow emphasis inside headings
MD026:
    punctuation: ".,;:!"

# MD029: Do not enforce ordered list numbering style
MD029: false

# MD033: Allow inline HTML (<br>, <details>, badges)
MD033: false

# MD036: Allow emphasis as heading (for stylistic purposes)
MD036: false

# MD041: First line doesn't need to be H1 (allow preambles)
MD041: false
