#!/bin/bash
# Build documentation for Primordium (mdBook + cargo doc)
set -e

echo "Building Primordium documentation..."

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Create output directory
mkdir -p docs/book/output

# Sync docs to src before mdbook build
echo -e "${BLUE}[0/4]${NC} Preparing source markdown..."
cp docs/wiki/BRAIN.md docs/book/src/wiki-brain.md 2>/dev/null || true
cp docs/wiki/GENETICS.md docs/book/src/wiki-genetics.md 2>/dev/null || true
cp docs/wiki/ECOSYSTEM.md docs/book/src/wiki-ecosystem.md 2>/dev/null || true
cp docs/wiki/HISTORY.md docs/book/src/wiki-history.md 2>/dev/null || true
cp docs/MANUAL.md docs/book/src/manual.md 2>/dev/null || true
cp docs/MANUAL_zh.md docs/book/src/manual_zh.md 2>/dev/null || true
cp README.md docs/book/src/readme.md 2>/dev/null || true
cp CHANGELOG.md docs/book/src/changelog.md 2>/dev/null || true
cp docs/CHANGELOG_zh.md docs/book/src/changelog_zh.md 2>/dev/null || true
cp ROADMAP.md docs/book/src/roadmap.md 2>/dev/null || true
cp ARCHITECTURE.md docs/book/src/architecture.md 2>/dev/null || true

echo -e "${BLUE}[1/4]${NC} Building mdBook..."
cd docs/book
mdbook build
cd ../..

echo -e "${BLUE}[2/4]${NC} Generating Cargo API documentation..."
# Generate docs for all crates
cargo doc --workspace --no-deps

# Copy crates' cargo doc output to book directory
echo -e "${BLUE}[3/4]${NC} Integrating API docs..."
mkdir -p docs/book/output/api
for crate in primordium_data primordium_core primordium_io primordium_net primordium_tui primordium_observer primordium_server primordium_tools; do
    if [ -d "target/doc/$crate" ]; then
        cp -r target/doc/$crate docs/book/output/api/
        echo "  Copied $crate docs"
    fi
done

echo -e "${BLUE}[4/4]${NC} Creating index.html linking to both doc types..."
cat > docs/book/output/api-index.html <<EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Primordium API Documentation</title>
    <style>
        body { font-family: sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }
        h1 { color: #2c3e50; }
        .crate-list { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin-top: 20px; }
        .crate-card { border: 1px solid #ddd; padding: 15px; border-radius: 5px; }
        .crate-card a { color: #3498db; text-decoration: none; }
        .crate-card a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <h1>Primordium API Documentation</h1>
    <p>Rust crate documentation generated by <code>cargo doc</code>.</p>
    <div class="crate-list">
EOF

for crate in primordium_data primordium_core primordium_io primordium_net primordium_tui primordium_observer primordium_server primordium_tools; do
    if [ -d "docs/book/output/api/$crate" ]; then
        echo "        <div class=\"crate-card\"><a href=\"$crate/index.html\"><h2>$crate</h2></a></div>" >> docs/book/output/api-index.html
    fi
done

cat >> docs/book/output/api-index.html <<EOF
    </div>
    <p><a href="../index.html">← Back to main documentation</a></p>
</body>
</html>
EOF



echo ""
echo -e "${GREEN}Documentation build complete!${NC}"
echo "Main docs: file://$(pwd)/docs/book/book/index.html"
echo "API docs:  file://$(pwd)/docs/book/output/api-index.html"
echo ""
echo "To serve locally:"
echo "  cd docs/book && mdbook serve --port 3000"
