pub mod brain;
pub mod config;
pub mod environment;
pub mod food;
pub mod history;
pub mod influence;
pub mod interaction;
pub mod lifecycle;
pub mod lineage_registry;
pub mod lineage_tree;
pub mod pathogen;
pub mod pheromone;
pub mod pressure;
pub mod snapshot;
pub mod sound;
pub mod spatial_hash;
pub mod systems;
pub mod terrain;

pub use brain::{BrainLogic, GenotypeLogic};
pub use influence::{InfluenceGrid, InfluenceSource};
pub use primordium_data::{Connection, Node, NodeType};
pub use terrain::TerrainLogic;
